// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxhlsmuxrdvcsykobwhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4aGxzbXV4cmR2Y3N5a29id2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTc1OTIsImV4cCI6MjA3MTQ3MzU5Mn0.Ecfhnqv0Aihkk8VoA_p-DypDy34CTbh5XcHBVxwVCN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});